package mfipr.dkf3.oracle;

import java.util.HashMap;
import java.util.Map;

public class InsertQueries {
    private static Map<String, String> insertQueryMap = new HashMap<>();

    public static Map<String, String> getInsertQueryMap() {
        insertQueryMap.put("bk_ogloszenia","INSERT INTO SL2014DKF.BK_OGLOSZENIA ( OGL_ID, OGL_ID_VER, OGL_ZAR_OGL_ID, OGL_NR_OGL, OGL_VER, OGL_VER_AKT, OGL_TYTUL, OGL_STATUS, OGL_VER_STATUS, OGL_DATA_SKL_OFR, OGL_DATA_PUBL, OGL_DATA_OST_ZM, OGL_DATA_PLAN_POD, OGL_NR_PROJ, OGL_W_KONTEKSCIE, OGL_ZAMOWIENIE_UZUP, OGL_WARUNKI_ZM_UMOWY, OGL_OFERTA_CZESCIOWA, OGL_ADR_OGL_NAZWA, OGL_ADR_OGL_UL, OGL_ADR_OGL_NR, OGL_ADR_OGL_KOD, OGL_ADR_OGL_MIASTO, OGL_ADR_OGL_TYP_ID, OGL_ADR_OGL_ID, OGL_ADR_OGL_KRAJ, OGL_ADR_OGL_WOJ, OGL_ADR_OGL_POW, OGL_ADR_OGL_GMI, OGL_KTO_UTWORZYL, OGL_DATA_UTWORZENIA, OGL_KTO_MODYFIKOWAL, OGL_DATA_MODYFIKACJI) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_oferty_zalaczniki","INSERT INTO SL2014DKF.BK_OFERTY_ZALACZNIKI (ZAL_ID, ZAL_NAZWA, ZAL_PLIK_NAZWA) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_dane_kontakt","INSERT INTO SL2014DKF.BK_OGL_DANE_KONTAKT (DK_ID, DK_OGL_ID_VER, DK_IMIE, DK_NAZWISKO, DK_TEL, DK_EMAIL) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_oferty_wybrane","INSERT INTO SL2014DKF.BK_OGL_OFERTY_WYBRANE (OFW_ID, OFW_OGL_ID, OFW_ZAL_ID, OFW_CENA, OFW_STATUS, OFW_OFERENT_NAZWA, OFW_OFERENT_ID_TYP, OFW_OFERENT_ID_NR, OFW_OFERENT_KRAJ, OFW_OFERENT_WOJ, OFW_OFERENT_POW, OFW_OFERENT_GMI, OFW_OFERENT_KOD_POCZ, OFW_OFERENT_MIASTO, OFW_OFERENT_UL, OFW_OFERENT_NR_UL) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_oferty_zlozone","INSERT INTO SL2014DKF.BK_OGL_OFERTY_ZLOZONE (OFZ_ID, OFZ_OGL_ID, OFZ_ZAL_ID, OFZ_CENA, OFZ_STATUS, OFZ_OFERENT_NAZWA, OFZ_OFERENT_ID_TYP, OFZ_OFERENT_ID_NR, OFZ_OFERENT_KRAJ, OFZ_OFERENT_WOJ, OFZ_OFERENT_POW, OFZ_OFERENT_GMI, OFZ_OFERENT_KOD_POCZ, OFZ_OFERENT_MIASTO, OFZ_OFERENT_UL, OFZ_OFERENT_NR_UL) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_pyt_odp","INSERT INTO SL2014DKF.BK_OGL_PYT_ODP (PYT_ID, PYT_OGL_ID, PYT_STATUS, PYT_NR, PYT_DATA_WYSLANIA, PYT_DATA_PUBLIKACJI, PYT_TRESC, ODP_STATUS, ODP_TRESC, ODP_DATA_PUBLIKACJI) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zalaczniki","INSERT INTO SL2014DKF.BK_OGL_ZALACZNIKI (ZAL_ID, ZAL_OGL_ID_VER, ZAL_NAZWA, ZAL_ROZSZERZENIE) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zam_cpv","INSERT INTO SL2014DKF.BK_OGL_ZAM_CPV (CPV_ID, CPV_ZAM_POZ_ID, CPV_KOD, CPV_NAZWA) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zam_harmonogram","INSERT INTO SL2014DKF.BK_OGL_ZAM_HARMONOGRAM (HAR_ID, HAR_ZAM_POZ_ID, HAR_DATA_POCZ, HAR_DATA_KON, HAR_PLAT_CZESC, HAR_OPIS) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zam_kryt_oceny","INSERT INTO SL2014DKF.BK_OGL_ZAM_KRYT_OCENY (KOC_ID, KOC_ZAM_ID, KOC_KRYT_CENOWE, KOC_OPIS) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zam_miejsca_real","INSERT INTO SL2014DKF.BK_OGL_ZAM_MIEJSCA_REAL (MR_ID, MR_ZAM_POZ_ID, MR_TYP, MR_KRAJ, MR_WOJ, MR_POW, MR_GMI, MR_MIASTO) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zam_warunki","INSERT INTO SL2014DKF.BK_OGL_ZAM_WARUNKI (WAR_ID, WAR_ZAM_POZ_ID, WAR_TYP, WAR_OPIS) WITH TMP_TABLE AS");
        insertQueryMap.put("bk_ogl_zamowienia","INSERT INTO SL2014DKF.BK_OGL_ZAMOWIENIA (ZAM_ID, ZAM_POZ_ID, ZAM_OGL_ID_VER, ZAM_TYTUL, ZAM_OFERT_WAR, ZAM_KATEGORIA, ZAM_PODKATEGORIA, ZAM_OPIS, ZAM_OKRES_GW, ZAM_WARTOSC_PRZEW) WITH TMP_TABLE AS");
        return insertQueryMap;
    }
}
